# Generated by Django 3.2.3 on 2021-06-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyImages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesupload',
            name='photo',
            field=models.ImageField(blank=True, upload_to='galleryImages/'),
        ),
    ]
