# Generated by Django 3.2.3 on 2021-07-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyImages', '0005_alter_imagesupload_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=50)),
                ('CategoryImage', models.ImageField(blank=True, upload_to='categoryPoster/')),
            ],
        ),
    ]
