# Generated by Django 3.2.3 on 2021-07-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyImages', '0006_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
